import { Router } from "express";
import authRoutes from "./authRoutes";
import uploadRoutes from "./uploadRoutes";
import productRoutes from "./productRoutes";
import categoryRoutes from "./categoryRoutes";
import offerRoutes from "./offerRoutes";
import couponRoutes from "./couponRoutes";
import siteSettingsRoutes from "./siteSettingsRoutes";
import permissionRoutes from "./permissionRoutes";
import userRoutes from "./userRoutes";
import newsletterRoutes from "./newsletterRoutes";
import reviewRoutes from "./reviewRoutes";
import bannerRoutes from "./bannerRoutes";
import customerAuthRoutes from "./customerAuthRoutes";
import customerRoutes from "./customerRoutes";
import skillRoutes from "./skillRoutes";
import sitemapRoutes from "./sitemapRoutes";
import adminCustomerRoutes from "./adminCustomerRoutes";
import adminSmsCampaignRoutes from "./adminSmsCampaignRoutes";
import { customerOrderRouter, adminOrderRouter } from "./orderRoutes";
import whatsappTestRoutes from "./whatsappTestRoutes";
import shiprocketRoutes from "./shiprocketRoutes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/upload", uploadRoutes);
router.use("/products", productRoutes);
router.use("/categories", categoryRoutes);
router.use("/offers", offerRoutes);
router.use("/coupons", couponRoutes);
router.use("/site-settings", siteSettingsRoutes);
router.use("/permissions", permissionRoutes);
router.use("/users", userRoutes);
router.use("/newsletter", newsletterRoutes);
router.use("/reviews", reviewRoutes);
router.use("/banners", bannerRoutes);
router.use("/customer/auth", customerAuthRoutes);
router.use("/customer/orders", customerOrderRouter);
router.use("/customer", customerRoutes);
router.use("/orders", adminOrderRouter);
router.use("/skills", skillRoutes);
router.use("/admin/customers", adminCustomerRoutes);
router.use("/admin/sms-campaigns", adminSmsCampaignRoutes);
router.use("/sitemap.xml", sitemapRoutes);
router.use("/whatsapp", whatsappTestRoutes);
router.use("/shiprocket", shiprocketRoutes);

export default router;