import https from "https";
import AppError from "./appError";
import { normalizeToE164 } from "./phoneUtils";

// ─────────────────────────────────────────────────────────────────────────────
// MSG91 Utility — SMS + OTP
//
// SMS_PROVIDER=msg91 activates this module.
//
// Required env vars:
//   MSG91_AUTH_KEY        — Your MSG91 authentication key
//   MSG91_SENDER_ID       — 6-letter DLT-approved sender ID  (SMS only)
//   MSG91_ROUTE           — SMS route (default "4" = transactional)
//   MSG91_COUNTRY         — Country code (default "91" = India)
//   MSG91_TEMPLATE_ID     — DLT Template ID for OTP SMS     (optional but recommended)
//   MSG91_ENTITY_ID       — DLT Entity ID                   (optional but recommended)
//   MSG91_OTP_TEMPLATE_ID — MSG91 OTP template ID           (OTP API — create in MSG91 dashboard)
//
// OTP API docs: https://docs.msg91.com/reference/send-otp
// ─────────────────────────────────────────────────────────────────────────────

// ── Internal HTTP helper ──────────────────────────────────────────────────────
interface HttpResponse {
  statusCode: number;
  body: string;
}

function postJson(
  url: string,
  payload: unknown,
  headers: Record<string, string>
): Promise<HttpResponse> {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify(payload);
    const request = https.request(
      url,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(data),
          ...headers,
        },
      },
      (response) => {
        let body = "";
        response.on("data", (chunk) => { body += chunk; });
        response.on("end", () => {
          resolve({ statusCode: response.statusCode ?? 500, body });
        });
      }
    );
    request.on("error", reject);
    request.write(data);
    request.end();
  });
}

function getJson(url: string, headers: Record<string, string>): Promise<HttpResponse> {
  return new Promise((resolve, reject) => {
    const request = https.request(url, { method: "GET", headers }, (response) => {
      let body = "";
      response.on("data", (chunk) => { body += chunk; });
      response.on("end", () => {
        resolve({ statusCode: response.statusCode ?? 500, body });
      });
    });
    request.on("error", reject);
    request.end();
  });
}

// ── Normalize mobile to 10-digit Indian number for MSG91 ─────────────────────
const getIndianMobile = (mobile: string): string =>
  normalizeToE164(mobile).replace(/^\+91/, "");

// ── Read required auth key ────────────────────────────────────────────────────
const getAuthKey = (): string => {
  const key = process.env.MSG91_AUTH_KEY;
  if (!key) {
    throw new AppError(
      "MSG91 is not configured. Set MSG91_AUTH_KEY in your .env file.",
      500
    );
  }
  return key;
};

// ═════════════════════════════════════════════════════════════════════════════
// 1.  MSG91 OTP API  (recommended for OTP verification in India)
//
//     Uses MSG91's managed OTP flow:
//       • /api/v5/otp        → send OTP
//       • /api/v5/otp/retry  → resend OTP
//       • /api/v5/otp/verify → verify OTP entered by user
//
//     MSG91 manages OTP generation internally when using this API.
//     Your backend still generates its own OTP and verifies via Redis
//     (see otpService.ts) — MSG91 OTP API is used ONLY for delivery.
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Send an OTP via MSG91's dedicated OTP API.
 *
 * @param mobile  10-digit Indian mobile number
 * @param otp     The OTP generated by otpService (6 digits)
 */
export const sendMsg91OTP = async (mobile: string, otp: string): Promise<void> => {
  const authKey     = getAuthKey();
  const templateId  = process.env.MSG91_OTP_TEMPLATE_ID;
  const mobile10    = getIndianMobile(mobile);

  if (!templateId) {
    // Fall back to plain SMS if no OTP template configured
    console.warn("[MSG91 OTP] MSG91_OTP_TEMPLATE_ID not set — falling back to plain SMS.");
    await sendMsg91SMS(mobile, `Your Kidroo verification code is: ${otp}. Valid for 5 minutes. Do not share it with anyone.`);
    return;
  }

  // Build OTP send URL
  const url =
    `https://control.msg91.com/api/v5/otp` +
    `?template_id=${encodeURIComponent(templateId)}` +
    `&mobile=91${mobile10}` +
    `&otp=${otp}`;

  try {
    const response = await getJson(url, { authkey: authKey });

    if (response.statusCode >= 400) {
      throw new AppError(
        `MSG91 OTP send failed (${response.statusCode}): ${response.body}`,
        500
      );
    }

    if (process.env.NODE_ENV !== "production") {
      console.log(`[MSG91 OTP] OTP sent to +91${mobile10}. Status: ${response.statusCode}`);
    }
  } catch (err: any) {
    if (err instanceof AppError) throw err;
    throw new AppError(
      `MSG91 OTP send error: ${err.message ?? "Unknown error"}`,
      500
    );
  }
};

/**
 * Resend OTP via MSG91's OTP retry API.
 * Call this when user requests a resend.
 *
 * @param mobile  10-digit Indian mobile number
 * @param retryType  "text" (default) or "voice"
 */
export const resendMsg91OTP = async (
  mobile: string,
  retryType: "text" | "voice" = "text"
): Promise<void> => {
  const authKey  = getAuthKey();
  const mobile10 = getIndianMobile(mobile);

  const url =
    `https://control.msg91.com/api/v5/otp/retry` +
    `?mobile=91${mobile10}` +
    `&retrytype=${retryType}`;

  try {
    const response = await getJson(url, { authkey: authKey });

    if (response.statusCode >= 400) {
      throw new AppError(
        `MSG91 OTP resend failed (${response.statusCode}): ${response.body}`,
        500
      );
    }
  } catch (err: any) {
    if (err instanceof AppError) throw err;
    throw new AppError(
      `MSG91 OTP resend error: ${err.message ?? "Unknown error"}`,
      500
    );
  }
};

// ═════════════════════════════════════════════════════════════════════════════
// 2.  MSG91 Plain SMS API  (used when OTP template is not configured,
//     or for non-OTP transactional messages)
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Send a plain transactional SMS via MSG91 v2 API.
 *
 * @param to    10-digit Indian mobile (or E.164 +91...)
 * @param body  SMS message text
 */
export const sendMsg91SMS = async (to: string, body: string): Promise<void> => {
  const authKey   = getAuthKey();
  const senderId  = process.env.MSG91_SENDER_ID;
  const route     = process.env.MSG91_ROUTE    || "4";
  const country   = process.env.MSG91_COUNTRY  || "91";
  const templateId = process.env.MSG91_TEMPLATE_ID;
  const entityId   = process.env.MSG91_ENTITY_ID;
  const mobile     = getIndianMobile(to);

  if (!senderId) {
    throw new AppError(
      "MSG91 SMS is not configured. Set MSG91_SENDER_ID in your .env file.",
      500
    );
  }

  const payload: Record<string, unknown> = {
    sender: senderId,
    route,
    country,
    sms: [
      {
        message: body,
        to: [mobile],
      },
    ],
  };

  if (templateId) payload.DLT_TE_ID = templateId;
  if (entityId)   payload.DLT_PE_ID = entityId;

  try {
    const response = await postJson(
      `https://api.msg91.com/api/v2/sendsms?country=${country}`,
      payload,
      { authkey: authKey }
    );

    if (response.statusCode >= 400) {
      throw new AppError(
        `MSG91 SMS failed (${response.statusCode}): ${response.body || "Unknown error"}`,
        500
      );
    }
  } catch (err: any) {
    if (err instanceof AppError) throw err;
    throw new AppError(
      `Failed to send SMS via MSG91: ${err.message ?? "Unknown error"}`,
      500
    );
  }
};
