import AppError from "./appError";
import { sendMsg91SMS, sendMsg91OTP, resendMsg91OTP } from "./msg91";
import { sendTwilioSMS } from "./twilio";

// ─────────────────────────────────────────────────────────────────────────────
// SMS / OTP Provider Router
//
// Set SMS_PROVIDER in your .env file:
//   SMS_PROVIDER=twilio   → uses Twilio for all SMS & OTP delivery
//   SMS_PROVIDER=msg91    → uses MSG91 OTP API (v5) for OTP,
//                           and MSG91 SMS API (v2) for plain SMS
//
// Provider is read at call-time so you can change it without restarting.
// ─────────────────────────────────────────────────────────────────────────────

export type SMSProvider = "twilio" | "msg91";

export const getSMSProvider = (): SMSProvider => {
  const provider = (process.env.SMS_PROVIDER || "twilio").trim().toLowerCase();

  if (provider === "twilio" || provider === "msg91") {
    return provider as SMSProvider;
  }

  throw new AppError(
    `Invalid SMS_PROVIDER "${provider}". Use "twilio" or "msg91".`,
    500
  );
};

// ═════════════════════════════════════════════════════════════════════════════
// sendOTP — Send an OTP code to a mobile number.
//
//   • Twilio  → plain SMS with the OTP embedded in the message body
//   • MSG91   → MSG91 OTP API v5 (template-based, DLT-compliant)
//               Falls back to plain SMS if MSG91_OTP_TEMPLATE_ID is not set.
//
// @param mobile  10-digit Indian mobile number
// @param otp     The 6-digit OTP generated by otpService
// @param context Human-readable context label for the SMS text (Twilio only)
//                e.g. "verification", "password reset"
// ═════════════════════════════════════════════════════════════════════════════
export const sendOTP = async (
  mobile: string,
  otp: string,
  context: "verification" | "password reset" = "verification"
): Promise<void> => {
  const provider = getSMSProvider();

  if (provider === "msg91") {
    // MSG91 OTP API v5 — uses your approved template on MSG91 dashboard.
    // If MSG91_OTP_TEMPLATE_ID is not set, sendMsg91OTP auto-falls back to plain SMS.
    await sendMsg91OTP(mobile, otp);
    return;
  }

  // Twilio — send plain SMS with OTP in the message body
  const contextLabel = context === "password reset" ? "password reset" : "verification";
  await sendTwilioSMS(
    mobile,
    `Your Kidroo ${contextLabel} code is: ${otp}. Valid for 5 minutes. Do not share it with anyone.`
  );
};

// ═════════════════════════════════════════════════════════════════════════════
// resendOTP — Resend an OTP.
//
//   • Twilio  → regenerates and re-sends plain SMS (caller passes new OTP)
//   • MSG91   → calls MSG91 OTP retry API (uses same session, no new OTP needed)
// ═════════════════════════════════════════════════════════════════════════════
export const resendOTP = async (
  mobile: string,
  otp: string,                         // new OTP (used by Twilio path only)
  context: "verification" | "password reset" = "verification"
): Promise<void> => {
  const provider = getSMSProvider();

  if (provider === "msg91") {
    // MSG91 manages the retry internally — just call retry API
    await resendMsg91OTP(mobile, "text");
    return;
  }

  // Twilio — send a fresh SMS with the new OTP
  const contextLabel = context === "password reset" ? "password reset" : "verification";
  await sendTwilioSMS(
    mobile,
    `Your Kidroo ${contextLabel} code is: ${otp}. Valid for 5 minutes. Do not share it.`
  );
};

// ═════════════════════════════════════════════════════════════════════════════
// sendSMS — Send a plain (non-OTP) transactional SMS.
//   Used for custom messages not covered by the OTP templates.
// ═════════════════════════════════════════════════════════════════════════════
export const sendSMS = async (to: string, body: string): Promise<void> => {
  const provider = getSMSProvider();

  if (provider === "msg91") {
    await sendMsg91SMS(to, body);
    return;
  }

  await sendTwilioSMS(to, body);
};
