import { sendMsg91SMS, sendMsg91OTP, resendMsg91OTP } from "./msg91";

// ═════════════════════════════════════════════════════════════════════════════
// sendOTP — Send an OTP code to a mobile number via MSG91
//
//   • MSG91   → MSG91 OTP API v5 (template-based, DLT-compliant)
//               Falls back to plain SMS if MSG91_OTP_TEMPLATE_ID is not set.
// ═════════════════════════════════════════════════════════════════════════════
export const sendOTP = async (
  mobile: string,
  otp: string,
  context: "verification" | "password reset" = "verification"
): Promise<void> => {
  await sendMsg91OTP(mobile, otp);
};

// ═════════════════════════════════════════════════════════════════════════════
// resendOTP — Resend an OTP via MSG91
// ═════════════════════════════════════════════════════════════════════════════
export const resendOTP = async (
  mobile: string,
  otp: string,
  context: "verification" | "password reset" = "verification"
): Promise<void> => {
  // Call the main send API again with the new OTP generated by our backend.
  // Using MSG91's /retry API would send the old OTP, causing a mismatch.
  await sendMsg91OTP(mobile, otp);
};

// ═════════════════════════════════════════════════════════════════════════════
// sendSMS — Send a plain (non-OTP) transactional SMS via MSG91.
// ═════════════════════════════════════════════════════════════════════════════
export const sendSMS = async (to: string, body: string): Promise<void> => {
  await sendMsg91SMS(to, body);
};

